channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- coverage
- graphviz =12.2.1
- hatchling =1.27.0
- hatch-vcs =0.5.0
- numpy =2.4.0
- owlrl =7.1.4
- pint =0.25.2
- rdflib =7.5.0
- pyshacl =0.30.1
- python >=3.11,<3.15
- python-graphviz =0.21
- requests =2.32.5
- typeguard =4.4.4
- flowrep =0.1.9
- networkx =3.5
